### ISSUE TITLE
Suspected label errors in verif pairs

### ISSUE THREAD

**Issue by SangwonSUH** [JaesungHuh/VoxSRC2023#1]
Firstly, many thanks for providing these valuable datasets!

I'd like to report a potential issue with some pairs in the `verif/VoxSRC2023_val.txt` file.
It seems that a few pairs may have incorrect labels.

Here are the pairs that are suspected of having falsely labeled data in the verif dataset:
```
1 011225.wav 060419.wav
1 060000.wav 048652.wav
1 010915.wav 049680.wav
1 003684.wav 018203.wav
1 017842.wav 061341.wav
1 020685.wav 039926.wav
1 014432.wav 048013.wav
1 007463.wav 018203.wav
1 043317.wav 020439.wav
1 029826.wav 044283.wav
```
While there may be additional cases, I have personally identified these ten through listening.
Could you review them and confirm whether they are correct?

Thank you 😃

**Comment by JaesungHuh** [comment]
Hi, Thanks for the participation.

I checked the labels of all 10 pairs you've reported. They are either from VoxCeleb or VoxMovies and the speaker ids are identical between each of the two wavfiles. So if they are wrong, they are label errors from those datasets.

I checked the videos of the corresponding wavfiles in the first few pairs and they seemed correct. So I'll leave these without changes.

FYI, believe it or not, the wavfiles in the second pair (060000.wav and 048652.wav) are both from Mark Ruffalo.

**Comment by SangwonSUH** [comment]
I believe that `060419.wav` is not suitable as an SV task because it has two dominant speakers.

https://github.com/JaesungHuh/VoxSRC2023/assets/17717477/6ec1c680-9a77-4c75-8ef6-4dce0463e09f

I'm interested in whether it would be appropriate to consider it as a "challenging" sample.

------
FYI. I've separated two voices with a separation model and attached it to the following 😀

https://github.com/JaesungHuh/VoxSRC2023/assets/17717477/bd253411-ae61-4ad3-a649-0463e302b711

https://github.com/JaesungHuh/VoxSRC2023/assets/17717477/8e88236d-8a82-4198-b62d-ac4cf7033c95

**Comment by JaesungHuh** [comment]
I thought I replied on this. I'm so sorry for the late reply.

Yes, I think it's the label noise in our val set and also the label noise in the VoxCeleb, where the wavfiles come from.

Could you use the val set without two pairs? It'll not affect the performance that much.

Thank you for your post.

BW,
Jaesung

**Comment by SangwonSUH** [comment]
I agree that there won't be a significant impact.
Should I close this issue, or leave it open for the others?
